# Generated by Django 3.2.16 on 2023-06-18 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basket',
            old_name='items',
            new_name='product',
        ),
    ]
